;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Sprinting",NewTagName="State.Abilities.Sprinting")
+GameplayTagRedirects=(OldTagName="State.Abilities",NewTagName="State.Ability")
+GameplayTagRedirects=(OldTagName="State.Abilities.Sprinting",NewTagName="State.Ability.Sprinting")
+GameplayTagRedirects=(OldTagName="State.Burning",NewTagName="State.Debuff.Burning")
+GameplayTagRedirects=(OldTagName="State.Dehydrated",NewTagName="State.Debuff.Dehydrated")
+GameplayTagRedirects=(OldTagName="State.Freezing",NewTagName="State.Debuff.Freezing")
+GameplayTagRedirects=(OldTagName="State.Poisoned",NewTagName="State.Debuff.Poisoned")
+GameplayTagRedirects=(OldTagName="State.Radiated",NewTagName="State.Debuff.Radiated")
+GameplayTagRedirects=(OldTagName="State.Starved",NewTagName="State.Vitals.Starved")
+GameplayTagRedirects=(OldTagName="State.Debuff.Dehydrated",NewTagName="State.Vitals.Dehydrated")
+GameplayTagList=(Tag="Ability.Movement.Sprint",DevComment="")
+GameplayTagList=(Tag="Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Effect.Heal",DevComment="")
+GameplayTagList=(Tag="Effect.Hydration",DevComment="")
+GameplayTagList=(Tag="Effect.Satiation",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Equipable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable.Pickupable",DevComment="")
+GameplayTagList=(Tag="Stat.Health.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Health.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Hunger.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Hunger.Max",DevComment="")
+GameplayTagList=(Tag="Stat.MovementSpeed.Base",DevComment="")
+GameplayTagList=(Tag="Stat.MovementSpeed.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Oxygen.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Oxygen.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Stamina.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Stamina.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Thirst.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Thirst.Max",DevComment="")
+GameplayTagList=(Tag="State.Ability.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Ability.Sprinting.End",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Burning",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Freezing",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Poisoned",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Radiated",DevComment="")
+GameplayTagList=(Tag="State.Vitals.Dehydrated",DevComment="")
+GameplayTagList=(Tag="State.Vitals.HasStamina",DevComment="")
+GameplayTagList=(Tag="State.Vitals.Starved",DevComment="")

