;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Effect.Heal",DevComment="")
+GameplayTagList=(Tag="Effect.Hydration",DevComment="")
+GameplayTagList=(Tag="Effect.Satiation",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Equipable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Interactable.Pickupable",DevComment="")
+GameplayTagList=(Tag="Stat.Health.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Health.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Hunger.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Hunger.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Oxygen.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Oxygen.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Stamina.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Stamina.Max",DevComment="")
+GameplayTagList=(Tag="Stat.Thirst.Current",DevComment="")
+GameplayTagList=(Tag="Stat.Thirst.Max",DevComment="")
+GameplayTagList=(Tag="State.Burning",DevComment="")
+GameplayTagList=(Tag="State.Dehydrated",DevComment="")
+GameplayTagList=(Tag="State.Freezing",DevComment="")
+GameplayTagList=(Tag="State.Poisoned",DevComment="")
+GameplayTagList=(Tag="State.Radiated",DevComment="")
+GameplayTagList=(Tag="State.Starved",DevComment="")

